name: Increment Version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  increment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read current version
        run: |
          version=$(cat version.txt)
          version=$((version + 1))
          echo $version > version.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add version.txt
          git commit -m "Auto increment version" || echo "No changes"

      - name: Push changes
        run: |
          git push